apiVersion: v1
kind: Service
metadata:
  name: haproxy-insights
  namespace: infra-k8s
  labels:
    app: haproxy-insights
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 32775
  selector:
    app: haproxy-insights
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: haproxy-insights
  namespace: infra-k8s
spec:
  selector:
    matchLabels:
      app: haproxy-insights
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy-insights
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: dckrio-hub-credentials
      containers:
        - name: app
          image: dckr/haproxy-insights:v1
          imagePullPolicy: Always
          args:
            - --main-stack-name {{ env_name }}
          env:
            - name: SERVICE_NAME
              value: haproxy-insights
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 50m
              memory: 32M
            requests:
              cpu: 50m
              memory: 32M


