{% set ucp_creds | b64encode %}
{"username":"admin","password":"{{ pass(infra/aws/ahokanson-us-east-1/swarm/ucp/password) }}"}
{% endset %}

apiVersion: v1
kind: Secret
metadata:
    name: ucp-credentials
    namespace: infra-k8s
type: Opaque
data:
    credentials: {{ ucp_creds }}

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: airboss
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: airboss
            image: dckr/airboss:6
            imagePullPolicy: Always
            env:
            - name: UCP_URL
              value: '{{ UCP_ROOT_URL }}'
          #   volumeMounts:
          #   - name: ucp-credentials
          #     readOnly: true
          #     mountPath: "/credentials"
          # volumes:
          # - name: ucp-credentials
          #   secret:
          #     secretName: ucp-credentials
          restartPolicy: Never
          imagePullSecrets:
          - name: dckrio-hub-credentials
